// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: shared/proto/product.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product represents a merchandise item in the catalog
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                              // UUID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                          // Product name
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`                                          // URL-friendly identifier
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`                                            // Stock Keeping Unit
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                            // Detailed description
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`                                  // 3-letter currency code (USD, EUR, etc)
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                      // Product status: draft, active, archived
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                          // Array of string tags
	Images        []*ProductImage        `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`                                      // Product images
	Categories    []*Category            `protobuf:"bytes,10,rep,name=categories,proto3" json:"categories,omitempty"`                             // Associated categories
	PriceCents    int64                  `protobuf:"varint,14,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`          // Unit price in minor currency units (e.g. cents)
	StockQuantity int32                  `protobuf:"varint,15,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"` // Units available for sale
	// Timestamps for record-keeping
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Null if not deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_shared_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// ProductImage represents an image with metadata attached to a product
type ProductImage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // UUID
	ProductId string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`  // Reference to parent product
	Url       string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                               // Image URL or path
	Alt       string                 `protobuf:"bytes,4,opt,name=alt,proto3" json:"alt,omitempty"`                               // Alt text for accessibility
	Position  int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`                    // Display order position
	IsPrimary bool                   `protobuf:"varint,6,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"` // Whether this is the main product image
	// Timestamps
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_shared_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductImage) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImage) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

func (x *ProductImage) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ProductImage) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ProductImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductImage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Category represents a product classification
type Category struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // UUID
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         // Category name
	Slug     string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`                         // URL-friendly identifier
	ParentId string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // Optional parent category ID
	Position int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`                // Display order position
	// Timestamps
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Null if not deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_shared_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Category) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Category) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// ProductList response for listing products
type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_shared_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProductList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ProductList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ProductRequest to get a specific product
type ProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*ProductRequest_Id
	//	*ProductRequest_Slug
	//	*ProductRequest_Sku
	Identifier    isProductRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_shared_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductRequest) GetIdentifier() isProductRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *ProductRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*ProductRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *ProductRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*ProductRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

func (x *ProductRequest) GetSku() string {
	if x != nil {
		if x, ok := x.Identifier.(*ProductRequest_Sku); ok {
			return x.Sku
		}
	}
	return ""
}

type isProductRequest_Identifier interface {
	isProductRequest_Identifier()
}

type ProductRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"` // Get by ID
}

type ProductRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"` // Get by slug
}

type ProductRequest_Sku struct {
	Sku string `protobuf:"bytes,3,opt,name=sku,proto3,oneof"` // Get by SKU
}

func (*ProductRequest_Id) isProductRequest_Identifier() {}

func (*ProductRequest_Slug) isProductRequest_Identifier() {}

func (*ProductRequest_Sku) isProductRequest_Identifier() {}

// ProductCreateRequest for creating a new product
type ProductCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"` // Optional, can be auto-generated
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"` // Default: USD
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`     // Default: draft
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Images        []*ProductImage        `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`                              // Optional at creation
	CategoryIds   []string               `protobuf:"bytes,9,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"` // Category IDs to associate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateRequest) Reset() {
	*x = ProductCreateRequest{}
	mi := &file_shared_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateRequest) ProtoMessage() {}

func (x *ProductCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateRequest.ProtoReflect.Descriptor instead.
func (*ProductCreateRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductCreateRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductCreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductCreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductCreateRequest) GetImages() []*ProductImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductCreateRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

// ProductUpdateRequest for updating an existing product
type ProductUpdateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Required
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug        string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Sku         string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Currency    string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status      string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Tags        []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CategoryIds []string               `protobuf:"bytes,9,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"` // Category IDs to associate
	// Fields mask for partial updates
	Fields        []string `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"` // List of fields to update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateRequest) Reset() {
	*x = ProductUpdateRequest{}
	mi := &file_shared_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateRequest) ProtoMessage() {}

func (x *ProductUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProductUpdateRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductUpdateRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductUpdateRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *ProductUpdateRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ListProductsRequest for filtering and pagination
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                              // 1-based page number
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`      // Items per page
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // Optional filter by category
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                               // Optional filter by tags
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                           // Optional filter by status
	Query         string                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`                             // Search query
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`             // Field to sort by
	SortDesc      bool                   `protobuf:"varint,8,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`      // Sort direction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_shared_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListProductsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListProductsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListProductsRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

// DeleteResponse after deleting a product
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_shared_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_proto_product_proto protoreflect.FileDescriptor

const file_shared_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x1ashared/proto/product.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x04\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12-\n" +
	"\x06images\x18\t \x03(\v2\x15.product.ProductImageR\x06images\x121\n" +
	"\n" +
	"categories\x18\n" +
	" \x03(\v2\x11.product.CategoryR\n" +
	"categories\x12\x1f\n" +
	"\vprice_cents\x18\x0e \x01(\x03R\n" +
	"priceCents\x12%\n" +
	"\x0estock_quantity\x18\x0f \x01(\x05R\rstockQuantity\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x92\x02\n" +
	"\fProductImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\tR\x03alt\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x06 \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x8d\x01\n" +
	"\vProductList\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"Z\n" +
	"\x0eProductRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slug\x12\x12\n" +
	"\x03sku\x18\x03 \x01(\tH\x00R\x03skuB\f\n" +
	"\n" +
	"identifier\"\x8c\x02\n" +
	"\x14ProductCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12-\n" +
	"\x06images\x18\b \x03(\v2\x15.product.ProductImageR\x06images\x12!\n" +
	"\fcategory_ids\x18\t \x03(\tR\vcategoryIds\"\x85\x02\n" +
	"\x14ProductUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12!\n" +
	"\fcategory_ids\x18\t \x03(\tR\vcategoryIds\x12\x16\n" +
	"\x06fields\x18\n" +
	" \x03(\tR\x06fields\"\xdf\x01\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\b \x01(\bR\bsortDesc\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd4\x02\n" +
	"\x0eProductService\x127\n" +
	"\n" +
	"GetProduct\x12\x17.product.ProductRequest\x1a\x10.product.Product\x12B\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x14.product.ProductList\x12@\n" +
	"\rCreateProduct\x12\x1d.product.ProductCreateRequest\x1a\x10.product.Product\x12@\n" +
	"\rUpdateProduct\x12\x1d.product.ProductUpdateRequest\x1a\x10.product.Product\x12A\n" +
	"\rDeleteProduct\x12\x17.product.ProductRequest\x1a\x17.product.DeleteResponseBKZIservices/product-service/internal/infrastructure/grpc/product_proto;protob\x06proto3"

var (
	file_shared_proto_product_proto_rawDescOnce sync.Once
	file_shared_proto_product_proto_rawDescData []byte
)

func file_shared_proto_product_proto_rawDescGZIP() []byte {
	file_shared_proto_product_proto_rawDescOnce.Do(func() {
		file_shared_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_product_proto_rawDesc), len(file_shared_proto_product_proto_rawDesc)))
	})
	return file_shared_proto_product_proto_rawDescData
}

var file_shared_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shared_proto_product_proto_goTypes = []any{
	(*Product)(nil),               // 0: product.Product
	(*ProductImage)(nil),          // 1: product.ProductImage
	(*Category)(nil),              // 2: product.Category
	(*ProductList)(nil),           // 3: product.ProductList
	(*ProductRequest)(nil),        // 4: product.ProductRequest
	(*ProductCreateRequest)(nil),  // 5: product.ProductCreateRequest
	(*ProductUpdateRequest)(nil),  // 6: product.ProductUpdateRequest
	(*ListProductsRequest)(nil),   // 7: product.ListProductsRequest
	(*DeleteResponse)(nil),        // 8: product.DeleteResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_shared_proto_product_proto_depIdxs = []int32{
	1,  // 0: product.Product.images:type_name -> product.ProductImage
	2,  // 1: product.Product.categories:type_name -> product.Category
	9,  // 2: product.Product.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: product.Product.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 5: product.ProductImage.created_at:type_name -> google.protobuf.Timestamp
	9,  // 6: product.ProductImage.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 7: product.Category.created_at:type_name -> google.protobuf.Timestamp
	9,  // 8: product.Category.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 9: product.Category.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 10: product.ProductList.products:type_name -> product.Product
	1,  // 11: product.ProductCreateRequest.images:type_name -> product.ProductImage
	4,  // 12: product.ProductService.GetProduct:input_type -> product.ProductRequest
	7,  // 13: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	5,  // 14: product.ProductService.CreateProduct:input_type -> product.ProductCreateRequest
	6,  // 15: product.ProductService.UpdateProduct:input_type -> product.ProductUpdateRequest
	4,  // 16: product.ProductService.DeleteProduct:input_type -> product.ProductRequest
	0,  // 17: product.ProductService.GetProduct:output_type -> product.Product
	3,  // 18: product.ProductService.ListProducts:output_type -> product.ProductList
	0,  // 19: product.ProductService.CreateProduct:output_type -> product.Product
	0,  // 20: product.ProductService.UpdateProduct:output_type -> product.Product
	8,  // 21: product.ProductService.DeleteProduct:output_type -> product.DeleteResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_shared_proto_product_proto_init() }
func file_shared_proto_product_proto_init() {
	if File_shared_proto_product_proto != nil {
		return
	}
	file_shared_proto_product_proto_msgTypes[4].OneofWrappers = []any{
		(*ProductRequest_Id)(nil),
		(*ProductRequest_Slug)(nil),
		(*ProductRequest_Sku)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_product_proto_rawDesc), len(file_shared_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_product_proto_goTypes,
		DependencyIndexes: file_shared_proto_product_proto_depIdxs,
		MessageInfos:      file_shared_proto_product_proto_msgTypes,
	}.Build()
	File_shared_proto_product_proto = out.File
	file_shared_proto_product_proto_goTypes = nil
	file_shared_proto_product_proto_depIdxs = nil
}
